config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  resources :subscribers, only: [:new, :create]

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'books', to: 'pages#books'
  get 'disclaimer', to: 'pages#disclaimer'
  get 'user_recipes', to: 'user_recipes#index'
  get 'user_recipes/:id', to: 'user_recipes#show', as: "user_recipe"
  resources :subscribers, only: [:new, :create]

  resources :recipes do
    resources :ingredients, only: [:new, :create, :edit, :update]
  end
  resources :ingredients, only: [:destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :description, presence: true
  validates :instructions, presence: true
  validates :cooking_time, presence: true
  validates :image, presence: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates_uniqueness_of :email
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

app/models/subscribers.rb
class Subscriber < ApplicationRecord
  validates_uniqueness_of :email
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    redirect_to root_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to root_path
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.recipe = @recipe
    if @ingredient.save
      redirect_to recipe_path(@recipe), notice: "ingredient added"
    else
      render :new, alert: "ingredient invalid or already exists"
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(ingredient_params)

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to recipes_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :recipe_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  http_basic_authenticate_with name: ENV["HTTP_NAME"], password: ENV["HTTP_PASSWORD"]
  def daystamp
    Time.now.strftime("%y%m%d").to_i
  end

  def index
    @recipes = Recipe.all

    number_generator = Random.new(daystamp)
    min_recipe_id = Recipe.minimum(:id)
    max_recipe_id = Recipe.maximum(:id)
    ids = @recipes.map { |r| r.id }
    random_recipe_id = number_generator.rand(min_recipe_id..max_recipe_id)
    if ids.include?(random_recipe_id)
      @recipe_of_the_day = Recipe.find(random_recipe_id )
    else
      @recipe_of_the_day = Recipe.last
    end

    @recipe = @recipe_of_the_day.id
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :instructions, :vegan, :vegetarian, :dairy_free, :gluten_free, :cooking_time, :image, :serves, :fact)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to root_path, notice: 'Great! You are now Subscribed'
    elsif Subscriber.where(email: @subscriber.email)
      redirect_to root_path, alert: "This email has already been taken"
    else
      redirect_to root_path, alert: 'Invalid Email, try again.'
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/controllers/user_recipes_controller.rb
class UserRecipesController < ApplicationController
  def daystamp
    Time.now.strftime("%y%m%d").to_i
  end

  def index
    @recipes = Recipe.all

    number_generator = Random.new(daystamp)
    min_recipe_id = Recipe.minimum(:id)
    max_recipe_id = Recipe.maximum(:id)
    ids = @recipes.map { |r| r.id }
    random_recipe_id = number_generator.rand(min_recipe_id..max_recipe_id)
    if ids.include?(random_recipe_id)
      @recipe_of_the_day = Recipe.find(random_recipe_id )
    else
      @recipe_of_the_day = Recipe.last
    end

    @recipe = @recipe_of_the_day.id
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

# every 24 hours, change the recipe of the day

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contact/new.html.erb
 <%= form_for @contact do |f| %>
    <% if flash[:error].present? %>
        <p> flash[:error]</p>
    <% end %>
    <%= f.label :name %> <br>
    <%= f.text_field :name, required: true %>

    <br>
    <%= f.label :email %> <br>
    <%= f.text_field :email, required: true %>

    <br>
    <%= f.label :message %> <br>
    <%= f.text_area :message, as: :text %>


    <%= f.label :nickname %> <br>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>


    <%= f.submit 'Send Message', class: "button" %>
  <% end %>

app/views/ingredients/edit.html.erb
<%= render partial: "shared/navbar" %>

<%= simple_form_for [@recipe, @ingredient] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/pages/home.html.erb
<%= render partial: "shared/anchor-link" %>

<div class="home-container">

  <!------------ navbar ------------>

  <%= render partial: "shared/navbar" %>

  <!------------ banner ------------>

  <div class="home-banner"><a id="top" style="position: absolute; top: 0;"></a>
    <div class="home-banner-box">
    </div>
  </div>

  <!------------ profile ------------>

  <div class="home-profile"><a id="Profile" style="position: absolute; top: 95vh;"></a>
    <div class="home-profile-box">
      <div class="home-profile-image-container">
        <div class="home-profile-image-border">
          <div class="home-profile-image">
          </div>
        </div>
      </div>
      <div class="home-profile-content">

        <h5>LUCY BURNEY (DipION) was one of the first qualified nutritional therapists to specialize in children’s health and wellbeing.</h5>
        <p>Her four books, <a href="https://www.amazon.co.uk/Optimum-Nutrition-Babies-Young-Children/dp/0749926228/ref=sr_1_1?dchild=1&keywords=lucy+burney&qid=1594390096&sr=8-1" target="_blank">Optimum Nutrition for Babies and Young Children</a>, <a href="https://www.amazon.co.uk/Lucy-Burney-Immunity-Healthy-Fighting/dp/B00I63AEUO/ref=sr_1_1?dchild=1&keywords=immunity+foods+lucy+burney&qid=1594391152&sr=8-1" target="_blank">Immunity Foods for Healthy Kids</a>, <a href="https://www.amazon.co.uk/Superfoods-Healthy-Kids-Childs-Fighting/dp/1844833658/ref=sr_1_1?dchild=1&keywords=superfoods+for+healthy+kids+lucy&qid=1595082620&sr=8-1" target="_blank">Superfoods for Healthy Kids</a>, and the highly successful, <a href="https://www.amazon.co.uk/Boost-Your-Childs-Immune-System/dp/074992442X/ref=sr_1_2?dchild=1&keywords=lucy+burney&qid=1594389948&sr=8-2" target="_blank">Boost Your Childs Immune System</a>, cover every growing stage of your child’s life from tot to teen.
        <p>Published internationally, Lucy gained a reputation for her common sense approach to children’s health. Her books also make being a great parent as easy and straightforward as possible.</p>

        <p>Lucy has frequently appeared on radio and TV, in newspapers and magazines and has contributed articles for magazines including <u>The Tesco Baby Club</u> and <u>Natural Parent</u>.</p>
        <p>She arms parents with the tools to raise strong, healthy and happy children. This has never been more relevant and more important for a rewarding life in the modern world.</p>

        <p>Lucy lives in Hampshire with her husband and four children.</p>

        <p class="letter-spacing">Read about <%= link_to "Lucy's Journey", about_path %> here</p>
      </div>
    </div>
  </div>

  <!------------ recipes ------------>

  <div class="home-recipes">
    <div class="home-recipes-box">
      <div class="home-recipes-content">
        <h2 class="home-recipes-title">New Recipes</h2>
        <p>Enjoy Lucy’s newest recipes, bursting with flavour, superfoods and nutrients to better support that healthy lifestyle we all aspire to have.</p>
      </div>
      <div class="home-recipe-images">
        <div class="home-recipe-image r-img r-img-1"></div>
        <div class="home-recipe-image r-img r-img-2"></div>
        <div class="home-recipe-image r-img-3"></div>
      </div>
      <button class="red-button"><%= link_to 'MORE RECIPES', user_recipes_path %></button>
    </div>
  </div>

  <!------------ books ------------>

  <%= render partial: "shared/books" %>

  <!------------ newsletter ------------>

  <%= render partial: "shared/newsletter" %>

  <!------------ footer ------------>

  <%= render partial: "shared/footer" %>

</div>

app/views/recipes/index.html.erb
<%= render partial: "shared/anchor-link" %>

<div class="recipes-index-container">

  <%= render partial: "shared/navbar" %>

  <div class="recipe-of-the-day-container"><a id="top" style="position: absolute; top: 0;"></a>
    <p>------------------------------</p>
    <%= link_to "new recipe", new_recipe_path %>
    <p>------------------------------</p>
    <div class="recipe-of-the-day-border">
      <div class="recipe-of-the-day">
        <div class="recipe-of-the-day-img-container">
          <div class="recipe-of-the-day-img" style="background-image: url('<%=cl_image_path @recipe_of_the_day.image.key, width: 320, height: 420, :fetch_format => :auto%>')"></div>
        </div>
        <div class="recipe-of-the-day-content-container">
          <div class="recipe-of-the-day-content">
            <h2 class="recipe-of-the-day-title">Recipe of the Day</h2>
            <h5><%= link_to @recipe_of_the_day.name, recipe_path(@recipe) %></h5>
            <p class="recipe-of-the-day-description"><%= @recipe_of_the_day.description.split(".")[0] %>...</p>
            <h4>INGREDIENTS</h4>
            <ul class="recipe-of-the-day-ingredient-list">
            <% @recipe_of_the_day.ingredients.first(3).each do |i| %>
            <li><%= i.name %></li>
            <% end %>
            </ul>
            <p>.......</p>
            <h4><%= link_to "SHOW MORE", recipe_path(@recipe_of_the_day) %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="user-recipe-section-container">
    <div><h2 style="text-align: center; font-size: 3em; padding-bottom: 0.5em; "> Lucy's Recipes </h2></div>
    <div class="user-recipe-grid-top">
      <div class="user-recipes-dietary-key">
        <p class="dietary-key-items">V: Vegan </p>
        <p class="dietary-key-items">Ve: Vegetarian </p>
        <p class="dietary-key-items">DF: Dairy Free </p>
        <p class="dietary-key-items">GF: Gluten Free</p>
      </div>
    </div>

    <div class="user-recipes-grid-container">
      <div class="user-recipes-grid">
        <% @recipes.each do |r| %>
          <div class="recipe-index-img" style="background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.35) 100%, rgba(255, 255, 255, 0) 104.37%), url('<%=cl_image_path r.image.key, width: 290, height: 365, :fetch_format => :auto, :quality => :auto%>')">
          <%= link_to recipe_path(r) do %>

            <div class="recipe-grid">
              <div class="recipe-type">
                <% if r.vegan %>
                  <p class="white">V</p>
                <% end %>

                <% if r.vegetarian %>
                    <p class="white">Ve</p>
                <% end %>

                <% if r.dairy_free %>
                  <p class="white">DF</p>
                <% end %>

                <% if r.gluten_free %>
                  <p class="white">GF</p>
                <% end %>
              </div>

              <div class="recipe-name">
                <h3><%= link_to r.name, recipe_path(r) %></h3>
              </div>

              <div class="cooking-time-and-serves">
                <p><i class="far fa-clock" style="color: white; padding: 0 0.5em;"></i><%= r.cooking_time %> mins</p>
                <p><i class="fas fa-user-friends" style="color: white; padding: 0 0.5em;"></i><%= r.serves == 10 ? "10+" : r.serves %></p>
              </div>
            </div>
          <% end %>

          </div>
        <% end %>
      </div>
    </div>

  </div>

  <%= render partial: "shared/books" %>

  <%= render partial: "shared/footer" %>

</div>

app/views/recipes/show.html.erb
<%= render partial: "shared/anchor-link" %>

<div class="recipes-show-container">

  <%= render partial: "shared/navbar" %>

  <div class="recipes-show-recipe-container"><a id="top" style="position: absolute; top: 0;"></a>
    <div class="recipes-show-recipe">
      <div class="recipe-show-img-container">
        <div class='recipe-show-img' style="background-image: url('<%=cl_image_path @recipe.image.key, width: 400, height: 480, :fetch_format => :auto%>')"></div>
      </div>

      <div class="recipe-show-content-container">
        <div class="recipe-show-content">
          <h3><%= @recipe.name %></h3>
          <p><%= link_to "edit recipe", edit_recipe_path %></p>
          <p><%= link_to "Delete recipe", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" } %></p>
          <div class="cooking-time-and-serves-show">
            <% mins = (@recipe.cooking_time.to_f % 60).to_i %>
            <% hours = ((@recipe.cooking_time - mins) / 60).to_i %>
            <p><i class="far fa-clock" style="padding: 0 0.5em;"></i><%= @recipe.cooking_time %> mins</p>
            <p><i class="fas fa-user-friends" style="padding: 0 0.5em;"></i><%= @recipe.serves %></p>
            <div class="recipe-dietary-info-container">
              <p class="recipe-dietary-info info-1"><%= "V" if @recipe.vegan %> </p>
              <p class="recipe-dietary-info">  <%= "Ve" if @recipe.vegetarian %> </p>
              <p class="recipe-dietary-info"> <%= "DF" if @recipe.dairy_free %> </p>
              <p class="recipe-dietary-info"> <%= "GF" if @recipe.gluten_free %> </p>
            </div>
          </div>

          <p><%= @recipe.description %></p>

          <p>------------------------</p>

          <h4 class="ingredients">INGREDIENTS</h4>
          <p><%= link_to "add ingredient", new_recipe_ingredient_path(@recipe) %></p>
          <ul>
          <% @recipe.ingredients.each do |i| %>
            <% if i.name.include?(":") %>
              <p>-------</p>
              <strong><%= i.name %></strong>
            <% else %>
              <li><%= i.name %></li>
            <% end %>
             <%= link_to "edit ingredient", edit_recipe_ingredient_path(@recipe, i) %>
            <%=  link_to "Delete ingredient", ingredient_path(i), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
          </ul>

          <p>------------------------</p>

          <h4 class="recipe-instructions">INSTRUCTIONS</h4>
          <ol>
          <% array = @recipe.instructions.split("/") %>
          <% array.each do |r| %>
            <% if r.include?(":") %>
              <p>-------</p>
              <strong><%= "#{r.split(' ')[0].capitalize} #{r.split(' ')[1..-1].join(' ')}" %></strong>
            <% else %>
              <li><%= "#{r.split(' ')[0].capitalize} #{r.split(' ')[1..-1].join(' ')}" %></li>
            <% end %>
          <% end %>
          </ol>

           <p>------------------------</p>

          <% if @recipe.fact != nil %>
            <h3>Super Nutrition fact</h3>
            <p><%= @recipe.fact %></p>
          <% else %>
          <% end %>

          <%= link_to "back", user_recipes_path %>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: "shared/books" %>

  <%= render partial: "shared/footer" %>

</div>

app/views/shared/_anchor-link.html.erb
<a href="#top"><i class="fas fa-chevron-up fa-lg arrow-bottom-right"></i></a>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="single-bluebell-img"></div>
    <a href="https://www.instagram.com/lucyburneynutrition/">@lucyburneynutrition</a>
    <div class="footer-img"></div>
    <div class="footer-icons">
      <a href="https://www.instagram.com/lucyburneynutrition/"><i class="fab fa-instagram footer-icon"></i></a>
      <a href="https://www.amazon.co.uk/s?k=lucy+burney&ref=nb_sb_noss_1"><i class="fab fa-amazon footer-icon"></i></a>
    </div>
    <button class="btn purple-button"><%= link_to "CONTACT", contact_path%></button>
    <div class="footer-links">
      <%= link_to "About", about_path %>
      <%= link_to "Recipes", user_recipes_path %>
      <%= link_to "Books", books_path %>
      <%= link_to "Disclaimer", disclaimer_path %>
    </div>
    <div class="footer-copyright">
      <p class="footer-p-copyright">© 2020 lucy burney all rights reserved</p>
      <p class="footer-p-copyright">site by otto burney</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-original">
  <div class="navbar-content">
    <div class="nav-icons">
      <a href="https://www.instagram.com/lucyburneynutrition/" target=”_blank”><i class="fab fa-instagram icon"></i></a>
      <a href="https://www.amazon.co.uk/s?k=lucy+burney&ref=nb_sb_noss_1" target=”_blank”><i class="fab fa-amazon icon"></i></a>
    </div>
    <%= link_to root_path do %>
    <div class="logo">
      <div class="logo-top">
        <h2 class="logo-lucy-burney">Lucy</h2>
        <div class="navbar-bluebell b-1"></div>
        <h2 class="logo-lucy-burney">Burney</h2>
      </div>
      <h3 class="logo-bottom">NUTRITION</h3>
    </div>
    <% end %>
    <span class="hamburger" style="font-size:1.5em;cursor:pointer" onclick="openNav()">&#9776;</span>
  </div>
</div>

<div id="myNav" class="overlay">
  <a class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
    <p><%= link_to "Home", root_path %></p>
    <p><%= link_to "About", about_path %></p>
    <p><%= link_to "Books", books_path %></p>
    <p><%= link_to "Recipes", user_recipes_path %></p>
    <p><%= link_to "Contact", contact_path %></p>
  </div>
</div>

<script>
  function openNav() {
    document.getElementById("myNav").style.height = "100%";
  }

  function closeNav() {
    document.getElementById("myNav").style.height = "0%";
  }
</script>

app/views/shared/_newsletter.html.erb
<div class="newsletter">
  <div class="newsletter-contents">
    <div class="newsletter-title">
      <h4>STAY IN TOUCH</h4>
      <p>Stay in touch via my newsletter. I share my newest recipes, tips, tricks and useful superfood facts. You may opt out at any time.</p>
    </div>
  <%= simple_form_for Subscriber.new, :as => :subscriber, :url => subscribers_path(@subscriber) do |f| %>
    <div class="newsletter-input"><%= f.input :email, label: false, placeholder: 'enter your email address here...' %></div>
    <div class="newsletter-subscribe-button"><%= f.button :submit, "SUBSCRIBE" %></div>
  <% end %>
  </div>
</div>

app/views/shared/_recipes.html.erb
<div class="recipe-of-the-day-container">
  <div class="recipe-of-the-day-border">
    <div class="recipe-of-the-day">
      <div class="recipe-of-the-day-img-container">
        <!-- <div class="recipe-of-the-day-img" style="background-image: url(<%= @recipe_of_the_day.image_url %>)"> -->

        </div>
      </div>
      <div class="recipe-of-the-day-content-container">
        <div class="recipe-of-the-day-content">
          <h2 class="recipe-of-the-day-title">Recipe of the day</h2>
          <h5><%= link_to @recipe_of_the_day.name, user_recipe_path(@recipe) %></h5>
          <p class="recipe-of-the-day-description"><%= @recipe_of_the_day.description.split(".")[0] %></p>
          <h4>INGREDIENTS</h4>
          <ul>
          <% @recipe_of_the_day.ingredients.first(6).each do |i| %>
          <li><%= i.name %></li>
          <% end %>
          </ul>
          <p>.......</p>
          <h4><%= link_to "SHOW MORE", user_recipe_path(@recipe_of_the_day) %></h4>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="user-recipes-grid-container">
  <div class="user-recipes-grid">
    <% @recipes.each do |r| %>
      <div class="recipe-index-img" style="background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.35) 100%, rgba(255, 255, 255, 0) 104.37%), url(<%= r.image_url %>)">
      <%= link_to user_recipe_path(r) do %>

        <div class="recipe-grid">
          <div class="recipe-type">

            <% if r.vegan %>
             <div class="white-box">
               <div class="diet-icon vegan"></div>
            </div>
            <% end %>

            <% if r.vegetarian %>
            <div class="white-box">
               <div class="diet-icon vegetarian"></div>
            </div>
            <% end %>

            <% if r.dairy_free %>
            <div class="white-box">
               <div class="diet-icon dairy_free"></div>
            </div>
            <% end %>

            <% if r.gluten_free %>
            <div class="white-box">
               <div class="diet-icon gluten_free"></div>
            </div>
            <% end %>

          </div>
          <div class="recipe-name">
            <h3><%= link_to r.name, user_recipe_path(r) %></h3>
          </div>
          <div class="cooking-time-and-serves">
            <p><%= r.cooking_time %> mins</p>
            <p>Serves <%= r.serves %></p>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_recipes/index.html.erb
<%= render partial: "shared/anchor-link" %>

<div class="recipes-index-container">

  <%= render partial: "shared/navbar" %>

  <div class="recipe-of-the-day-container"><a id="top" style="position: absolute; top: 0;"></a>
    <div class="recipe-of-the-day-border">
      <div class="recipe-of-the-day">
        <div class="recipe-of-the-day-img-container">
          <div class="recipe-of-the-day-img" style="background-image: url('<%=cl_image_path @recipe_of_the_day.image.key, width: 320, height: 420, :fetch_format => :auto%>')"></div>
        </div>
        <div class="recipe-of-the-day-content-container">
          <div class="recipe-of-the-day-content">
            <h2 class="recipe-of-the-day-title">Recipe of the Day</h2>
            <h5><%= link_to @recipe_of_the_day.name, user_recipe_path(@recipe) %></h5>
            <p class="recipe-of-the-day-description"><%= @recipe_of_the_day.description.split(".")[0] %>...</p>
            <h4>INGREDIENTS</h4>
            <ul class="recipe-of-the-day-ingredient-list">
            <% @recipe_of_the_day.ingredients.first(3).each do |i| %>
            <li><%= i.name %></li>
            <% end %>
            </ul>
            <p>.......</p>
            <h4><%= link_to "SHOW MORE", user_recipe_path(@recipe_of_the_day) %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="user-recipe-section-container">
    <div><h2 style="text-align: center; font-size: 3em; padding-bottom: 0.5em; "> Lucy's Recipes </h2></div>
    <div class="user-recipe-grid-top">
      <div class="user-recipes-dietary-key">
        <p class="dietary-key-items">V: Vegan </p>
        <p class="dietary-key-items">Ve: Vegetarian </p>
        <p class="dietary-key-items">DF: Dairy Free </p>
        <p class="dietary-key-items">GF: Gluten Free</p>
      </div>
    </div>

    <div class="user-recipes-grid-container">
      <div class="user-recipes-grid">
        <% @recipes.each do |r| %>
          <% return "" if r.id == nil %>
          <div class="recipe-index-img" style="background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.35) 100%, rgba(255, 255, 255, 0) 104.37%), url('<%=cl_image_path r.image.key, width: 290, height: 365, crop: "fill", :fetch_format => :auto, :quality => :auto%>')">
          <%= link_to user_recipe_path(r) do %>

            <div class="recipe-grid">
              <div class="recipe-type">
                <% if r.vegan %>
                  <p class="white">V</p>
                <% end %>

                <% if r.vegetarian %>
                    <p class="white">Ve</p>
                <% end %>

                <% if r.dairy_free %>
                  <p class="white">DF</p>
                <% end %>

                <% if r.gluten_free %>
                  <p class="white">GF</p>
                <% end %>
              </div>

              <div class="recipe-name">
                <h3><%= link_to r.name, user_recipe_path(r) %></h3>
              </div>

              <div class="cooking-time-and-serves">
                <p><i class="far fa-clock" style="color: white; padding: 0 0.5em;"></i><%= r.cooking_time %> mins</p>
                <p><i class="fas fa-user-friends" style="color: white; padding: 0 0.5em;"></i><%= r.serves == 10 ? "10+" : r.serves %></p>
              </div>
            </div>
          <% end %>

          </div>
        <% end %>
      </div>
    </div>

  </div>

  <%= render partial: "shared/books" %>

  <%= render partial: "shared/footer" %>

</div>